services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  collector:
    build: .
    command: python collector/main.py
    depends_on:
      - postgres
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs

volumes:
  pg_data:
  
