"""Initial schema

Revision ID: 31cdded52da9
Revises: 
Create Date: 2025-07-31 02:29:55.359453

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31cdded52da9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if "digests" not in inspector.get_table_names():
        op.create_table('digests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_digests_source'), 'digests', ['source'], unique=False)
        op.create_index(op.f('ix_digests_url'), 'digests', ['url'], unique=True)
    
    if "rave_articles" not in inspector.get_table_names():
        op.create_table('rave_articles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('developer_focus', sa.Boolean(), nullable=False),
        sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_rave_articles_source'), 'rave_articles', ['source'], unique=False)
        op.create_index(op.f('ix_rave_articles_url'), 'rave_articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rave_articles_url'), table_name='rave_articles')
    op.drop_index(op.f('ix_rave_articles_source'), table_name='rave_articles')
    op.drop_table('rave_articles')
    op.drop_index(op.f('ix_digests_url'), table_name='digests')
    op.drop_index(op.f('ix_digests_source'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
